name: app_anotacoes
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  flutter:
    sdk: flutter
  flutter_mobx: ^2.1.1
  get_it: ^7.6.4
  mobx: ^2.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0

flutter:
  uses-material-design: true
